### ISSUE TITLE
octave: missing header file (ida/ida_dense.h)

### ISSUE THREAD

**Issue by ekenberg** [schoeps/homebrew-science#2]
Trying to install octave from your tap because I need the qt gui for plots. I'm following this: http://www.schoeps.org/home/2017/10/octave-on-macos-with-gui/ except it seems I must enter the full path to your repo, or else homebrew tries to install octave from homebrew-core.

```brew install schoeps/homebrew-science/octave --HEAD --with-qt```

However, compilation fails with this error:

```
`libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -Iliboctave -I./liboctave -I./liboctave/array -Iliboctave/numeric -I./liboctave/numeric -Iliboctave/operators -I./liboctave/operators -I./liboctave/system -I./liboctave/util -I./libinterp/octave-value -Ilibinterp -I./libinterp -I./libinterp/operators -Ilibinterp/parse-tree -I./libinterp/parse-tree -Ilibinterp/corefcn -I./libinterp/corefcn -I./liboctave/wrappers -I/usr/local/opt/hdf5/include -I/usr/local/Cellar/graphicsmagick/1.3.26_2/include/GraphicsMagick -I/usr/local/Cellar/libsndfile/1.0.28/include -fPIC -D_THREAD_SAFE -pthread -Wall -W -Wshadow -Wold-style-cast -Wformat -Wpointer-arith -Wwrite-strings -Wcast-align -Wcast-qual -I/usr/local/Cellar/libsndfile/1.0.28/include -g -O2 -c libinterp/dldfcn/audioread.cc  -fno-common -DPIC -o libinterp/dldfcn/.libs/libinterp_dldfcn_audioread_la-audioread.o
libinterp/dldfcn/__ode15__.cc:44:14: fatal error: 'ida/ida_dense.h' file not found
#    include <ida/ida_dense.h>
             ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [libinterp/dldfcn/libinterp_dldfcn___ode15___la-__ode15__.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2`
```

**Comment by schoeps** [comment]
It's a recent incompatibility with the development version of Octave (Number [52475](https://savannah.gnu.org/bugs/?52475)). One possible fix is to downgrade sundials below version 3. I am still checking what is less effort, explaining how to downgrade or actually fixing the bug. Do you know how to downgrade the formula? If yes, then this would be the quickest solution.

**Comment by lanery** [comment]
I am running into the same incompatibility issue -- a fix would be great!

**Comment by ekenberg** [comment]
I thought I knew how to downgrade but it appears I don't. Googling 'homebrew downgrade' yields a lot of old and conflicting information, stuff which doesn't seem to work anymore ('brew versions' etc). I'm at a loss here, sorry.

**Comment by schoeps** [comment]
I pushed the old sundials 2.7 to my repository. The following should work:
```
brew uninstall sundials # remove any installed version
brew install schoeps/homebrew-science/sundials # install old 2.7
brew pin sundials # ask homebrew not to update
brew install octave --HEAD --with-qt --with-java
``` 

Can you confirm that this works?

**Comment by ekenberg** [comment]
It still insist on installing 3.1.0:

```~$ brew install schoeps/homebrew-science/sundials
==> Installing sundials from schoeps/science
==> Downloading https://homebrew.bintray.com/bottles-science/sundials-3.1.0.sierra.bottle.tar.gz```

**Comment by schoeps** [comment]
can you do try again (probably after calling `brew update`). I checkin in the recent version of sundials and not the old one, sorry.

**Comment by ekenberg** [comment]
Ok after installing sundials 2.7 and pinning it, I try to install octave but it fails:

``` 
$ brew install schoeps/homebrew-science/octave --HEAD --with-qt --with-java
==> Installing octave from schoeps/science
Error: You must `brew unpin sundials` as installing schoeps/science/octave requires the latest version of pinned dependencies```

**Comment by schoeps** [comment]
Strange. I did not see that error. What happens if you unpin? Does brew update sundials? (maybe we are lucky...).

**Comment by ekenberg** [comment]
If I unpin sundials, installing octave upgrades sundials to 3.1.0.

**Comment by schoeps** [comment]
Ok, I had a better idea: I added a new formula "sundials27". This is similar like homebrew core is doing it for some formulae. You can uninstall sundials and just reinstall octave and everything should work

**Comment by ekenberg** [comment]
Thank you, octave could finally build with qt! Unfortunately, plots show up at 25% size - I'm guessing some issue with octave-qt and retina display?

**Comment by ekenberg** [comment]
What's even worse, trying to use the other graphic backends (gnuplot / fltk) results in segmentation fault when closing the plot windows. Same thing when removing your custom octave and installing the default prebuilt one. Not sure how to fix this :/

**Comment by schoeps** [comment]
I know how to fix the scaling issue (yes it‘s a retina issue). There is patch that was probably removed when the homebrew core people removed the qt support. I will fix that tonight. You may be able to circumvent the problem by rescaling your resolution (I believe Apple calls it „more space“).

Personally, I use for plotting gnuplot and I do not see any problems neither with my GUI-enabled version of octave nor the original homebrew one. Not sure that I can help you with that. Maybe reinstalling gnuplot (I recommend `brew install gnuplot —HEAD —with-qt —with-cairo`) helps.

**Comment by ekenberg** [comment]
Thank you for your efforts. My problem with gnuplot is that it doesn't support patch(), so when I try to plot like a cube, I get

```
octave> error: __gnuplot_draw_axes__: gnuplot (as of v4.2) only supports 3-D filled triangular patches
error: called from
    __gnuplot_draw_axes__ at line 721 column 19
    __gnuplot_draw_figure__ at line 172 column 17
    __gnuplot_drawnow__ at line 86 column 5
```

fltk works, more-or-less, but crashes octave-cli

I'm using octave-qt on Linux and that works nicely so I was hoping that would solve the problems on mac. Currently there doesn't seem to exist any fully working plot backend for mac.

**Comment by schoeps** [comment]
This looks like you might have gnuplot version 4.2 installed? Hombrew ships with 5.2.2. Head should give you a checkout from the 5.3 branch.

**Comment by ekenberg** [comment]
I have 5.2.2 installed. No 4.2 on the system.

```
$ gnuplot --version
gnuplot 5.2 patchlevel 2
```

**Comment by schoeps** [comment]
The retina does not work anymore, I need to check it, sorry. That will take some timme

**Comment by schoeps** [comment]
I have joined forces with @dpo at http://github.com/dpo/homebrew-openblas. Is that issue still open? If yes, please try e.g.
`
brew install dpo/openblas/octave --verbose --with-java --devel --with-qt
`
I am about to delete that repository here.
