### ISSUE TITLE
Calling 'depends_on :hg' is disabled!

### ISSUE THREAD

**Issue by pkedrosky** [schoeps/homebrew-science#5]
Getting an error when I try to update Octave on Brew: 

Error: Calling 'depends_on :hg' is disabled!
Use 'depends_on "mercurial"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/octave.rb:12:in `block in <class:Octave>'

**Comment by pkedrosky** [comment]
Ah, I didn't realize. 

Updated to the new tap, and got the following non-critical error:

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/octave.rb:48:in `<class:Octave>'
Please report this to the dpo/openblas tap!

**Comment by schoeps** [comment]
Thanks! It will be fixed in the next update of the formula!

**Comment by schoeps** [comment]
Thanks! It will be fixed in the next update of the formula!
